# Generated by Django 5.1.6 on 2025-02-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='todo.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
